output:
  logstash:
    enabled: true
    hosts:
      - elk:5044
    timeout: 15
    # tls:
    #   certificate_authorities:
    #   - /etc/pki/tls/certs/logstash-beats.crt

filebeat:
  prospectors:
    # -
    #   paths:
    #     - /var/log/syslog
    #     - /var/log/auth.log
    #   document_type: syslog
    -
      paths:
        - /widget-service.log
      document_type: spring
      multiline:
        pattern: '^\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2}[.]\d{3}'
        negate: false
        match: after
