output:
  logstash:
    enabled: true
    hosts:
      - elk:5044
    timeout: 15
    tls:
      certificate_authorities:
      - /etc/pki/tls/certs/logstash-beats.crt

filebeat:
  prospectors:
    -
      paths:
        - /var/log/syslog
        - /var/log/auth.log
      document_type: syslog
    -
      paths:
        - widget-service.log
      document_type: spring
      multiline:
        pattern: '^[[:space:]]+|^Caused by:'
        negate: false
        match: after
